language: python



before_install:

  - pip install awscli



jobs:

  include:

  - stage: build and push ap docker image to aws ecr

    script:

      - eval $(aws ecr get-login --no-include-email)

      - docker build -t $python_NAME . --target app-python

      - docker tag $python_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$python_NAME:latest

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$python_NAME:latest

      - docker build -t $redis_NAME . --target app-redis

      - docker tag $redis_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$redis_NAME:latest

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$redis_NAME:latest


  - stage: run ap tests

    script: echo "Test1 Finish"

  - stage: deploy ap to aws batch

    script: skip

    

notifications:

  slack:

    on_pull_requests: true

    rooms:
     - juwai:fbVrH3u9xkfC95YsIFFsCcbO

    on_success: always # default: always

    on_failure: always # default: always
