language: python

before_install:

  - pip install awscli

jobs:

  include:

  - stage: build and push app docker image to aws ecr

    script:

      - echo `aws --version`

      - echo Logging in to Amazon ECR...

      - eval $(aws ecr get-login --no-include-email)

      - echo Entered the build phase...

      - docker build -t $python_NAME . --target app-python

      - echo Tag and Push the docker images to aws ecr...

      - docker tag $python_NAME:HW-287 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$python_NAME:HW-287

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$python_NAME:HW-287

      - docker build -t $redis_NAME . --target app-redis

      - docker tag $redis_NAME:HW-287 $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$redis_NAME:HW-287

      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$redis_NAME:HW-287

  - stage: run ap tests

    script: echo "Test1 Finish"

  - stage: Deploy app to aws ecs...

    script:

      - echo Updating aws ecs task definitions...

      - aws ecs update-service --cluster "ecs-poc" --service "ecs_poc_new" --force-new-deployment


notifications:

  slack:

    on_pull_requests: true

    rooms:
     - juwai:fbVrH3u9xkfC95YsIFFsCcbO

    on_success: always # default: always

    on_failure: always # default: always
